// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfH805gy4um3bvEsY1mRfVBWspKAlM56M',
    appId: '1:182680078004:web:c3306237a9354f3a23b9e1',
    messagingSenderId: '182680078004',
    projectId: 'gym-app-f5906',
    authDomain: 'gym-app-f5906.firebaseapp.com',
    storageBucket: 'gym-app-f5906.firebasestorage.app',
    measurementId: 'G-1NH81VJS5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBppwNrtSlq7lxKB8qNgArz-Bj7CB1EsjM',
    appId: '1:182680078004:android:d6ea06c2a9092c8f23b9e1',
    messagingSenderId: '182680078004',
    projectId: 'gym-app-f5906',
    storageBucket: 'gym-app-f5906.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALOno8MOBnqDj9FtxQdT04S8j2yzKz3Dw',
    appId: '1:182680078004:ios:9578a2e948dfce9e23b9e1',
    messagingSenderId: '182680078004',
    projectId: 'gym-app-f5906',
    storageBucket: 'gym-app-f5906.firebasestorage.app',
    iosBundleId: 'com.example.unigym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALOno8MOBnqDj9FtxQdT04S8j2yzKz3Dw',
    appId: '1:182680078004:ios:9578a2e948dfce9e23b9e1',
    messagingSenderId: '182680078004',
    projectId: 'gym-app-f5906',
    storageBucket: 'gym-app-f5906.firebasestorage.app',
    iosBundleId: 'com.example.unigym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfH805gy4um3bvEsY1mRfVBWspKAlM56M',
    appId: '1:182680078004:web:d46e04cc6c0b8ebd23b9e1',
    messagingSenderId: '182680078004',
    projectId: 'gym-app-f5906',
    authDomain: 'gym-app-f5906.firebaseapp.com',
    storageBucket: 'gym-app-f5906.firebasestorage.app',
    measurementId: 'G-JCV3CPMXQD',
  );
}
